/***************************************************************************
*  $MCI Módulo de definição: Dado
*
*  Arquivo gerado:              DADO.H
*  Letras identificadoras:      DAD
*
*  Projeto: INF 1301 	Projeto jogo gamão via terminal
*  Autores: elu - Emanuel Lima Umbelino
*           jpk - João Pedro Kalil
*           phs - Pedro Henrique Soares
*
*  $HA Histórico de evolução:
*     Versão  Autor    Data      Observações
*     1.00     phs   18/abr/2019 Início do desenvolvimento
*
*  $ED Descrição do módulo
*     Este módulo implementa um conjunto simples de funções para manipular
*     e obter os valores de um conjunto de dados.
*
***************************************************************************/

/***********************************************************************
*
*  $FC Função: DAD  Joga os dados
*
*  $ED Descrição da função
*     Gera dois números aleatórios
*
***********************************************************************/

void DAD_JogarDados(void);

/***********************************************************************
*
*  $FC Função: DAD 	Obtem valor do dado1
*
*  $FV Valor retornado
*     dado1
*
***********************************************************************/

int DAD_obtemDado1();

/***********************************************************************
*
*  $FC Função: DAD 	Obtem valor do dado2
*
*  $FV Valor retornado
*     dado2
*
***********************************************************************/

int DAD_obtemDado2();

/********** Fim do módulo de definição: Módulo dados **********/