
/***************************************************************************
*
*  $MCD Módulo de definição: Módulo Dado Pontos
*
*  Arquivo gerado:              DADOPONTOS.H
*  Letras identificadoras:      DPT
*
*  Projeto: Disciplina INF 1301
*  Gestor:  DI/PUC-Rio
*  Autores: elu - Emanuel Lima Umbelino
*        jpk - João Pedro Kalil
*        phs - Pedro Henrique Soares
*
*  $HA Histórico de evolução:
*     Versão   Autores	  Data           Observações
*      1.00    elu	  	17/04/2019     Inicializado projeto
*
*  $ED Descrição do módulo
*			Este módulo contém o tipo abstrato de dados da estrutura Dado Pontos.
*			Serve para saber o valor da partida, dobra-lo e saber quem pode dobrar o valor da partida.
*			
*
***************************************************************************/
 